CREATE_USERS = """
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    telegram_id BIGINT UNIQUE NOT NULL,
    username VARCHAR(255),
    role VARCHAR(32) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
"""

CREATE_EVENTS = """
CREATE TABLE IF NOT EXISTS events (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIME,
    end_date DATE,
    end_time TIME,
    place VARCHAR(255),
    description TEXT,
    cost DECIMAL(10, 2) DEFAULT 0,
    image_file_id VARCHAR(255),
    max_participants INTEGER,
    reminder_3days BOOLEAN NOT NULL DEFAULT FALSE,
    reminder_1day BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
"""

CREATE_EVENT_IMAGES = """
CREATE TABLE IF NOT EXISTS event_images (
    id SERIAL PRIMARY KEY,
    event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    file_id VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
"""

ALTER_EVENTS_PLACE_NULL = """
ALTER TABLE events
    ALTER COLUMN place DROP NOT NULL;
"""

ALTER_EVENTS_TIME_NULL = """
ALTER TABLE events
    ALTER COLUMN time DROP NOT NULL;
"""

ALTER_EVENTS_ADD_END_DATE = """
ALTER TABLE events
    ADD COLUMN IF NOT EXISTS end_date DATE;
"""

ALTER_EVENTS_ADD_END_TIME = """
ALTER TABLE events
    ADD COLUMN IF NOT EXISTS end_time TIME;
"""

CREATE_REGISTRATIONS = """
CREATE TABLE IF NOT EXISTS registrations (
    id SERIAL PRIMARY KEY,
    event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL DEFAULT 'going',
    registered_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(event_id, user_id)
);
"""

CREATE_DISCUSSIONS = """
CREATE TABLE IF NOT EXISTS discussions (
    id SERIAL PRIMARY KEY,
    event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
"""

STATEMENTS = (
    CREATE_USERS,
    CREATE_EVENTS,
    ALTER_EVENTS_PLACE_NULL,
    ALTER_EVENTS_TIME_NULL,
    ALTER_EVENTS_ADD_END_DATE,
    ALTER_EVENTS_ADD_END_TIME,
    CREATE_EVENT_IMAGES,
    CREATE_REGISTRATIONS,
    CREATE_DISCUSSIONS,
)

